# Generated by Django 6.0.3 on 2026-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mot de passe généré'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Doit changer le mot de passe'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_was_changed',
            field=models.BooleanField(default=False, verbose_name='Mot de passe modifié'),
        ),
    ]
