# Generated by Django 6.0.3 on 2026-03-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='N°')),
                ('noms', models.CharField(max_length=150, verbose_name='NOMS')),
                ('prenoms', models.CharField(blank=True, max_length=150, null=True, verbose_name='PRENOMS')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='DATE DE NAISSANCE')),
                ('num_secu', models.CharField(blank=True, max_length=100, null=True, verbose_name='NUM SECU')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, null=True, verbose_name='LIEU DE NAISSANCE')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='CONTACT')),
                ('lieu_enrolement', models.CharField(blank=True, max_length=150, null=True, verbose_name="LIEU D'ENROLEMENT")),
                ('rangement', models.CharField(max_length=100, verbose_name='RANGEMENT')),
                ('statut', models.CharField(blank=True, max_length=100, null=True, verbose_name='STATUT')),
                ('date_delivrance', models.DateField(blank=True, null=True, verbose_name='DATE DE DELIVRANCE')),
                ('noms_normalized', models.CharField(db_index=True, editable=False, max_length=150)),
                ('prenoms_normalized', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=150)),
                ('num_secu_normalized', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=100)),
                ('contact_normalized', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=50)),
                ('source_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fichier source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Client CMU',
                'verbose_name_plural': 'Clients CMU',
                'ordering': ['noms', 'prenoms'],
                'indexes': [models.Index(fields=['noms'], name='clients_cli_noms_394dca_idx'), models.Index(fields=['prenoms'], name='clients_cli_prenoms_68200a_idx'), models.Index(fields=['date_naissance'], name='clients_cli_date_na_46442a_idx'), models.Index(fields=['rangement'], name='clients_cli_rangeme_c62f2c_idx'), models.Index(fields=['statut'], name='clients_cli_statut_d69dca_idx'), models.Index(fields=['lieu_enrolement'], name='clients_cli_lieu_en_cf3634_idx'), models.Index(fields=['noms_normalized', 'prenoms_normalized'], name='clients_cli_noms_no_72b5fc_idx'), models.Index(fields=['num_secu_normalized'], name='clients_cli_num_sec_4fc740_idx')],
            },
        ),
    ]
