# Generated by Django 6.0.3 on 2026-03-14 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel (.xlsx)')], max_length=10, verbose_name='Type de fichier')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importé le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ANALYZED', 'Analysé'), ('CONFIRMED', 'Confirmé'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Nombre total de lignes')),
                ('new_rows', models.PositiveIntegerField(default=0, verbose_name='Nouvelles lignes')),
                ('duplicate_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes en doublon')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes mises à jour')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes ignorées')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
            ],
            options={
                'verbose_name': "Lot d'import",
                'verbose_name_plural': "Lots d'import",
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(verbose_name='Ligne du fichier')),
                ('incoming_data', models.JSONField(verbose_name='Données entrantes')),
                ('match_type', models.CharField(choices=[('NUM_SECU', 'Correspondance par numéro sécu'), ('IDENTITY', 'Correspondance par identité'), ('PARTIAL', 'Correspondance partielle')], max_length=20, verbose_name='Type de correspondance')),
                ('decision_status', models.CharField(choices=[('PENDING', 'En attente'), ('KEEP_EXISTING', 'Garder l’existant'), ('UPDATE_EXISTING', 'Mettre à jour l’existant'), ('SKIP', 'Ignorer')], default='PENDING', max_length=20, verbose_name='Décision')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='imports.importbatch', verbose_name="Lot d'import")),
                ('matched_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_duplicates', to='clients.client', verbose_name='Client correspondant')),
            ],
            options={
                'verbose_name': 'Doublon détecté',
                'verbose_name_plural': 'Doublons détectés',
                'ordering': ['row_index'],
                'unique_together': {('import_batch', 'row_index')},
            },
        ),
    ]
